### ISSUE TITLE
Warehouse Tracking

### ISSUE THREAD

**Issue by jonvin006** [OpenCLTBrigade/cmpd-holiday-gift#169]
- [ ] Need to have visibility of whether or not a child was already adopted.
- [ ] Need to be able to keep track of how many toys have been collected for each child.
- [ ] All Warehouse forms should be able to be printed for individual families from the “Show” Screen.

Would love if this was a QR code that brought up the Family Information and then a radio button to select the status of the child.
Family Information would be: Div#-RA-Family#, Last Name, # of kids in household
Child Info would be: Child#, First Name, Age, Gender, # of Toys, Status Options
If this is a QR code, add that to the Packing Slip
Once all children in the family are marked completed the whole family is marked completed.

**Things to track in the warehouse:**
- Toy donations
- Children status
- Bikes & their status
- Helmets
- Food boxes and gift cards

**Stages of the warehouse (verify with Ryan and set a default)**
- In Warehouse
- Adopted or Available
- Being shopped for
- In box
- Completed
- Out for Delivery
